# conda env create -f environment-no-build.yml
# cuda10.2+pytorch1.12+python3.10+lightning1.9.3
name: midx
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - abseil-cpp=20211102.0
  - absl-py=1.3.0
  - aiohttp=3.8.3
  - aiosignal=1.2.0
  - async-timeout=4.0.2
  - attrs=22.1.0
  - blas=1.0
  - blinker=1.4
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.01.10
  - cachetools=4.2.2
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cryptography=39.0.1
  - cudatoolkit=10.2.89
  - ffmpeg=4.3
  - freetype=2.12.1
  - frozenlist=1.3.3
  - fsspec=2023.4.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.4
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - idna=3.4
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lightning-utilities=0.7.1
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=6.0.2
  - ncurses=6.4
  - nettle=3.7.3
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - oauthlib=3.2.2
  - openh264=2.1.1
  - openssl=1.1.1t
  - packaging=23.0
  - pandas=1.5.3
  - pillow=9.4.0
  - pip=23.0.1
  - protobuf=3.20.3
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pyjwt=2.4.0
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.10.11
  - python-dateutil=2.8.2
  - pytorch=1.12.0
  - pytorch-lightning=1.9.3
  - pytorch-mutex=1.0
  - pytz=2022.7
  - pyyaml=6.0
  - re2=2022.04.01
  - readline=8.2
  - requests=2.29.0
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - setuptools=66.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tensorboard=2.11.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tk=8.6.12
  - torchaudio=0.12.0
  - torchmetrics=0.11.2
  - torchvision=0.13.0
  - tqdm=4.65.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2023c
  - urllib3=1.26.15
  - werkzeug=2.2.3
  - wheel=0.38.4
  - xz=5.4.2
  - yaml=0.2.5
  - yarl=1.8.1
  - zlib=1.2.13
  - zstd=1.5.5
