learner: adam
weight_decay: 0
learning_rate: 0.001
scheduler: ~

monitor_metric: ~
early_stop_mode: min
early_stop_patience: 100

# temperature of softmax
temperature: 1



epochs: 1000
num_workers: 4
batch_size: 256
eval_batch_size: 256

init_range: 0.01

fix_seed: True
seed: 10


sampler: ~
num_cluster: 32
pop_mode: 1
sphere_alpha: 100
rff_temp: 4.0
rff_dim: 32
